import './strings'



export function transcribe(code: string) {
    return code
        // .replace_fr(";", '!')
        .replace_fr("rn", ';')
        .replace_fr("be", '=')
        .replace_fr("rizz", 'let')
        .replace_fr("waffle", 'console.log')
        .replace_fr("sus", 'if')
        .replace_fr("fake", 'null')
        .replace_fr("impostor", 'else')
        .replace_fr("nah", '!=')
        .replace_fr("fr", '==')
        .replace_fr("btw", '&&')
        .replace_fr("carenot", '|')
        .replace_fr("bruh", 'fn')
        .replace_fr("nerd", 'math')
        .replace_fr("yall", 'for')
        .replace_fr("smol", '<')
        .replace_fr("thicc", '>')
        .replace_fr("nocap", 'true')
        .replace_fr("cap", 'false')
        .replace_fr("fuck_around", 'try')
        .replace_fr("find_out", 'catch')
        .replace_fr("clapback", 'exec')
        .replace_fr("yap", 'input')
        .replace_fr("minus", "-")
        .replace_fr("plus", "+")
        .replace_fr("minusminus", "--")
        .replace_fr("plusplus", "++")
        .replace_fr("times", "*")
        .replace_fr("divided by", "/")
        .replace_fr("bye", "exit")
        .replace_fr("hollup", "setTimeout")
        .replace_fr("yappacino", "setInterval")
        .replace_fr("beplus", "+=")
        .replace_fr("beminus", "-=")
        .replace_fr("betimes", "*=")
        .replace_fr("bedivided", "/=")
        .replace_fr("then", "->")
        .replace_fr("skibidi", "const")
        .replace_fr("yeet", "return")
        .replace_fr("gyatt", "get")
        .replace_fr("sigma", '"use strict"')
        .replace(/: number/g, '')
        .replace(/: string/g, '')
        .replace(/: object/g, '')
        .replace(/: boolean/g, '')
};